apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  selector: 
    matchLabels:
      app: angular
  replicas: 1
  template:
    metadata:
      labels:
        app: angular
    spec: 
      containers:
      - name: angular
        image: dhartl231198/k3s-dashboard
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: angular-service
spec:
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort