apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dashboard
spec:
  selector: 
    matchLabels:
      app: k8s-dashboard
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-dashboard
    spec: 
      containers:
  
      - name: k8s-dashboard
        image: dhartl231198/k8s-dashboard
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
 name: k8s-dashboard
spec:
 selector:
   app: k8s-dashboard
 ports:
 - protocol: TCP
   port: 80
   nodePort: 30086
 type: NodePort
 